### ISSUE TITLE
Amex cards

### ISSUE THREAD

**Issue by adamskinner** [PawelDecowski/jquery-creditcardvalidator#51]
Hi, 

Having a bit of trouble identifying American Express cards.  As well as my real card number some of these test amex numbers dont seem to work:

http://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

**Comment by PawelDecowski** [comment]
Hi @adamskinner 

When making such claims *please* provide a link to a demo ([CodePen](http://codepen.io), [JSFiddle](http://jsfiddle.net), etc). I really don’t have the time to test all reported supposedly not working numbers.

By looking at the link you’ve provided, these numbers should work. They start with 37 and are 15 digits long — definitely supported.

I’ll happily look into it if you can link to a demo that shows these numbers aren’t recognised.

**Comment by adamskinner** [comment]
Hi @PawelDecowski 

Sorry - your quite right. Amex card do work.

I had an error in my code and then tried your main website (http://jquerycreditcardvalidator.com/)

Because an amex card graphic didn't come up - I wrongly assumed it was broken.

Regards

Adam

**Comment by PawelDecowski** [comment]
Hi @adamskinner 

You weren’t the only one to assume something was broken because the demo doesn’t support all the cards that the plugin supports. In the most recent update I included a help text under the CC field that says which cards are supported by the demo. Hopefully that will help avoid confusion!
