### ISSUE TITLE
Include validation to Aura CreditCard

### ISSUE THREAD

**Issue by paulorudolph07** [PawelDecowski/jquery-creditcardvalidator#75]
first , I enjoyed the plugin and you guys are to be congratulated . As a suggestion , you guys can put a validation for the Aura card

**Comment by PawelDecowski** [comment]
Thanks!

What’s Aura card?

Could you provide a source of IIN ranges for Aura cards?

**Comment by PawelDecowski** [comment]
@paulorudolph07 ?

**Comment by douggr** [comment]
**Aura** is Brazilian brand I think, the pattern is /^50/.

**Comment by monecchi** [comment]
Yeah that would be great to have validation for Aura.

**Comment by PawelDecowski** [comment]
@douggr 

`/^50/` is MasterCard so I can’t use that to match Aura.

Is Aura actually a card brand (like Visa or MasterCard) or just an issuer?

**Comment by monecchi** [comment]
@douggr Aura is a brand which belongs to the BNP Paribas French Group and also seems to be managed by another corporation called Cetelem widely active both in Brazil, Portugal and other european countries. Their portfolio is consisted of around 3,5 million credit cards – 1 million of those already carry the Mastercard brand and the rest are still issued with the Aura brand.

I've made a brief research and indeed since 2009, the French Group and the Cetelem corporation have been developing a complete [migration](http://www.cetelem.com.br/novidade/Migracao.html) process to Mastercard, so the Aura brand will be obsolete and out of the market soon. 

As for the Aura pattern validation, I use a Brazilian payment method on my woocommerce powered website which matches Aura cards gracefully, the plugin is called Cielo WooCommerce Webservice, it relies on jquery.payment plugin which is now supported by default in woocommerce.

You can have a look at its code here: https://github.com/greguly/cielo-woocommerce/blob/master/assets/js/credit-card/checkout-webservice.js

**Comment by PawelDecowski** [comment]
So it basically starts with 5078?

The question is: should I add a card, which “will be out of the market soon“?

**Comment by monecchi** [comment]
@paulorudolph07  I believe it is a valid request from a UX perspective. The migration process might take some time, so until there I see it as a UX fix in order to match the old card brand while the migration is not complete.

**Comment by PawelDecowski** [comment]
But `50` is a range reserved for Maestro. I’m worried that there will be collisions. Since there is no official source for Aura, I’m very hesitant to add it.

**Comment by douggr** [comment]
@monecchi thank you for the great explanation! Awesome.

I double checked a validator we developed back in the days, they use `/^50/` for Aura. Awkwardly all UnitTests begins with `5078`, actually `50786`. But I'm not sure if the "6" matters.

I'd quote @PawelDecowski opinion on this:
> But 50 is a range reserved for Maestro. I’m worried that there will be collisions. Since there is no 
> official source for Aura, I’m very hesitant to add it.

**Comment by mateuspadua** [comment]
@ceasbz If you still need this, follow the solution here #82, last comment . Abraços :)

**Comment by uncle9999** [comment]
#104

**Comment by uncle9999** [comment]
#133

**Comment by uncle9999** [comment]
#33

**Comment by uncle9999** [comment]
#73

**Comment by uncle9999** [comment]
#22

**Comment by uncle9999** [comment]
@PawelDecowski
