### ISSUE TITLE
Add new Mastercard range

### ISSUE THREAD

**Issue by d3bugg3r** [PawelDecowski/jquery-creditcardvalidator#79]
Start from Oct 2016 Mastercard is introducing a new range of numbers with the following first 6 digits range, 222100-272099

please add it up

**Comment by PawelDecowski** [comment]
Thanks. Source?

**Comment by reamaor** [comment]
@PawelDecowski since we work heavily in the industry it was a direct request by several psp's.
but you can see articles here: 

[](https://www.realexpayments.com/blog/mastercard-to-introduce-new-card-numbers/)
[](https://www.forte.net/blog/mastercard-bin-range-coming/)
[](https://en.wikipedia.org/wiki/Bank_card_number)

**Comment by kyleschulz** [comment]
I'm looking for the same update. We've currently implemented a work around until this has been updated.

**Comment by divbox** [comment]
looking for same update as well.  thanks

**Comment by ianleeder** [comment]
I too am in need of this.  I found a decent reference on the topic:
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html
While they don't seem state it clearly on that page, the linked PDFs all state in the opening sentence:

> MasterCard is rolling out an additional range of six-digit BINs (222100-272099).

For the moment I've manually updated my javascript, but I would prefer not to deviate from the published version.  I <s>stole the regex</s> _learnt_ from [here](http://www.regular-expressions.info/creditcard.html), and stripped out all the extra `[0-9]` criteria since they seem redundant, leaving this complete Mastercard regex:
`pattern: /^(5[1-5]|222[1-9]|22[3-9]|2[3-6]|27[01]|2720)/,`

Works with the only test card number I have (2221 0000 0000 0009).  Haven't found an online site to generate test numbers in the new range yet.

**Comment by paulyeo** [comment]
I've received an email from a rep and for the time being implemented ianleeder's patch above. There is an implementation deadline of 30 Sep 2016 so am hoping to update from main branch once an official update is released... Thanks!
---
Dear Merchant
As a step to increasing the supply of BINs, MasterCard is in the process of issuing cards within BIN range from 222100 to 272099. This will be in addition to the existing BIN range from 510000 to 559999.
Prior to issuing the new 2 series BIN cards MasterCard is working with all the participants to ensure that the entire eco-system can recognize and process cards issued in the new BIN range just as they process the existing 5 series BINs 510000 to 559999.
In this context the E-commerce space requires some additional work due to the unique aspects of processing, such as the role of payment service providers, 3-D secure validation and gateways.
The purpose of this note is to make sure that you, as a participant in the E-com space, are aware of the introduction of MasterCard branded cards issued with the new 2 series BINs.
If you are a
1.      Merchant hosting your own payment page, or
2.      Payment facilitator providing any payment page / hosting services to any merchants, or
3.      Software provider to merchants who have their own payment page, or
4.      M-POS payment facilitator or aggregator, or
5.      Play any role in the transaction processing cycle
and
if any of the following have any validation routine based on the card number prior to sending the transaction onward either to the gateway or for 3-D secure validation
1.      Merchant’s own payment page
2.      Payment page hosted by you in your capacity as a payment service provider
3.      Loyalty/promotion related software where rewards are linked to the brand of the card
4.      Any other routine in the processing sequence that validates based on card number before sending the transaction to the next stage
then you will have to make all the necessary changes to your software and databases to make sure that cards issued in the new 2 BIN range from 222100 to 272099 pass seamlessly through the filters and checks, just as the cards issued with the existing 5 series BINs 510000 to 559999 do.
The above are examples of scenarios that definitely require work to be done to achieve 2 series BIN acceptance. You may like to review all parts of your system to identify other areas that may require work to achieve the same objective.
It is critical that all of these changes are executed and tested prior to 30 September 2016.
We would appreciate if you could carry out an assessment of your systems in this regard, and send us an email to confirm one of the following:
1.      You have reviewed all the elements in your systems and processes which may be impacted by this new BIN range 222100 to 272099 and confirm that system can handle them without the need for any software or database changes, or
2.      Your systems, database or software do require changes, and indicate the date by which you will be able to complete all the required changes, test and confirm to us that your systems are 2 Series BIN ready. When the necessary changes have been completed and tested please send us an email to confirm completion.
Thanks in advance for your help to implement this critical project.

**Comment by PawelDecowski** [comment]
Thanks, guys. This will be included in the next version, to be released in September.

**Comment by szepgerg** [comment]
Hi, I made this regexp for the new BIN range. Could you please check if is valid?

`(2221[0-9]{2}|222[2-9][0-9]{2}|22[3-9][0-9]{3}|2[3-6][0-9]{4}|27[0-1][0-9]{3}|2720[0-9]{2})`

**Comment by ntxt** [comment]
Hi Paweł, I've made a PR before I found the above conversation. Anyway, thanks and looking forward to the next ver.

**Comment by eggsurplus** [comment]
Had trouble catching all cases with the examples above. This worked for the needed ranges:
`^5$|^5[1-5][0-9]{0,14}$|^2[2]?[2]?$|^2221[0-9]{0,12}$|^222[3-9][0-9]{0,12}$|^22[3-9][0-9]{0,13}$|^2[3-6][0-9]{0,14}$|^2[7]?$|^27[2]?$|^27[0-1][0-9]{0,12}$|^2720[0-9]{0,12}$`

**Comment by akhilgoyal** [comment]
@PawelDecowski could you provide some update on this please?

**Comment by PawelDecowski** [comment]
@akhilgoyal I’ll do my best to finish it tonight.

**Comment by dtayloresw** [comment]
Hi @PawelDecowski thanks for this. Any updates?

**Comment by PawelDecowski** [comment]
v1.1 will be released tonight.

**Comment by dtayloresw** [comment]
Thanks @PawelDecowski for this much appreciated
